### PR TITLE
Added support for openssl to run.yaml

### PR DESCRIPTION
**Pull request by sinamhdv**
added openssl to run.yaml, which currently performs sha256 on a sample input file.

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
@sinamhdv please wrapt the commit description at ~70 characters per line. Looks good besides that.

**Comment by razvand** [comment]
The generated `run` script gives out:

```
[    0.261271] ERR:  [appelfloader] <elf_load.c @  135> openssl: ELF executable is not position-independent!                                                                                                                                  
[    0.262257] ERR:  [appelfloader] <elf_load.c @  703> openssl: Parsing of ELF image failed: Exec format error (-8)
```

To fix that, you need to update the `command` option with: `/lib64/ld-linux-x86-64.so.2 --library-path /lib /bin/openssl sha256 < input.txt`

**Comment by razvand** [comment]
> The generated `run` script gives out:
> 
> ```
> [    0.261271] ERR:  [appelfloader] <elf_load.c @  135> openssl: ELF executable is not position-independent!                                                                                                                                  
> [    0.262257] ERR:  [appelfloader] <elf_load.c @  703> openssl: Parsing of ELF image failed: Exec format error (-8)
> ```
> 
> To fix that, you need to update the `command` option with: `/lib64/ld-linux-x86-64.so.2 --library-path /lib /bin/openssl sha256 < input.txt`

This is actually solved by this PR: https://github.com/unikraft/dynamic-apps/pull/95

Aim for this to get merged and that will probably solve this.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
