### PR TITLE
Adjust to the rename `ukarch_sysregs` -> `ukarch_sysctx`

### PR DESCRIPTION
**Pull request by mogasergiu**
Propagate Unikraft's `sysregs` API names have changed to `sysctx`.
While at it, remove no longer used FSGSBASE related read/write methods.

GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1346

### CODE REVIEW

**Review by michpappas — APPROVED** [review]
Reviewed-by: Michalis Pappas <michalis@unikraft.io>

**Comment by mogasergiu** [comment]
Depends on Unikraft [#1346](https://github.com/unikraft/unikraft/pull/1346)

**Review by michpappas — APPROVED** [review]
Reviewed-by: Michalis Pappas <michalis@unikraft.io>

**Review by razvanvirtan — APPROVED** [review]
Looks good to me, thanks @mogasergiu!

Reviewed-by: Razvan Virtan <virtanrazvan@gmail.com>

**Review by andreistan26 — APPROVED** [review]
Looks good!

Reviewed-by: Andrei Stan [andreistan2003@gmail.com](mailto:andreistan2003@gmail.com)

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
