### PR TITLE
Make VDSO creation work for cross-compilation and Darwin

### PR DESCRIPTION
**Pull request by skuenzer**
This commit reworks the compilation rules for the VDSO so that they can be easily cross-compiled and be compiled on a Darwin environment (MacOS).
The following improvements are implemented:
- The build-system provided compiler and tool commands are called instead of calling the tools (e.g., `gcc`) directly which would create an incompatible VDSO when cross-compiling.
- Any build artifact is created under the appelfloader build path (and not within the sources path).
- Recompilation dependencies are correctly stated.
- The step that adds symbol placeholders is separated from compiling the VDSO template.
- Compiling and linking of the VDSO is done with `-nostartfiles` which avoids the unnnecessary inclusion of start files, like `crt0.o`. Those startfiles are not needed for the VDSO because it provides only some symbols and code that is looked up and used by a libc (and dynamic linker) for performing faster system calls.

### CODE REVIEW

**Review by i-Pear — APPROVED** [review]
Thanks for better integrating VDSO with the build system, looks good to me.

**Comment by i-Pear** [comment]
An unimportant question:
Why do we need `-nostartfiles`? `crt0.o` should not have been linked in the first place, because we have `-nostdlib` and `-shared`.

Do shared libraries have start files by default? I can't find them using `objdump -D`.

**Comment by skuenzer** [comment]
> An unimportant question: Why do we need `-nostartfiles`? `crt0.o` should not have been linked in the first place, because we have `-nostdlib` and `-shared`.
> 
> Do shared libraries have start files by default? I can't find them using `objdump -D`.

You are right and in fact I was also wondering about this at some point. Just now, I re-tried without `-nostartfiles` and it worked as well. In general, what made it work for me with cross-compiling on an Arm Mac is to handover `-nostdlib` to both: compiling and linking. We had it originally only at one of the commands and `gcc` tried looking up for `crt0.o`. On that Mac environment, I had a `x86_64-elf` gcc cross compiler but no stdlib files available. This way I got aware of this problem.

👍🏻 I am going to remove `-nostartfiles` from the PR.

**Review by i-Pear — APPROVED** [review]
LGTM, thanks.

Reviewed-by: Tianyi Liu <i.pear@outlook.com>

**Review by John-Ted — APPROVED** [review]
Everything works well.
Reviewed-by: Ioan-Teodor Teugea <ioan_teodor.teugea@stud.acs.upb.ro>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
