### PR TITLE
Add support for loading ELF images from the root file system (InitRD support)

### PR DESCRIPTION
**Pull request by csvancea**
This PR is built upon #9.

### Changes

This change introduces support for InitRD file system. Previously, initrd used to point to the Linux ELF image that was supposed to be loaded, meaning that we could not populate the RamFS with a cpio archive and therefore we could not run dynamically-linked Linux ELFs (because `.so` dependencies could not be loaded).

Now, if `CONFIG_LIBVFSCORE_ROOTFS_INITRD` is set, app-elfloader will load the ELF image and its dependencies (if any) from the file system.

Also, this PR removes the custom app name build configuration. It seems that the normal configuration already supports this use-case (running apps with multiple "personalities"). Moreover, the option seems to be broken. For example, setting `CONFIG_APPELFLOADER_CUSTOMAPPNAME=n` and providing an empty command line (`-a ""`) is supposed to set `argv[0]` to whatever was given as initrd. However, what the ELF file sees is an empty arguments set (`argc=0`), which I believe is not the desired result.

### Running app-elfloader with InitRD

First of all, make sure that you configure app-elfloader to use InitRD as root file system: `make menuconfig` > Library Configuration > VFS core > Default root filesystem (InitRD)

Then, create a cpio archive with the ELF file and its dependencies (libraries, config files etc). The ramdisk will be initialized with the contents of this archive.

```console
$ tree
.
├── helloworld
├── helloworld_staticpie
├── ld-linux-x86-64.so.2
└── libc.so.6

0 directories, 4 files
$ ls | bsdcpio -o --format newc > ../rootfs.cpio
6679 blocks
```

The cpio archive is passed as initrd. Also, the first argument you provide must be the name of the ELF binary, relative to rootfs.

For example: 
```console
$ qemu-guest -k app-elfloader_kvm-x86_64 -i rootfs.cpio -a "/helloworld_staticpie arg1 arg2"
[...]
[    0.535052] Info: [libukboot] <boot.c @  369> Calling main(4, ['../my-unikernel/apps/app-elfloader/build/app-elfloader_kvm-x86_64', '/helloworld_staticpie', 'arg1', 'arg2'])
[    0.584745] Info: [appelfloader] <main.c @   82> Image at 0x403800018, len 945624 bytes
[    0.605945] Info: [appelfloader] <main.c @  109> ELF program loaded to 0x403901000-0x4039d8b00 (883456 B), entry at 0x4039097a0
[0] /helloworld_staticpie
[1] arg1
[2] arg2
```

Or, a dynamically-linked ELF:

```console
$ qemu-guest -k app-elfloader_kvm-x86_64 -i rootfs.cpio -a "/ld-linux-x86-64.so.2 --library-path / /helloworld arg1 arg2"
[...]
[    0.520383] Info: [libukboot] <boot.c @  369> Calling main(7, ['../my-unikernel/apps/app-elfloader/build/app-elfloader_kvm-x86_64', '/ld-linux-x86-64.so.2', '--library-path', '/', '/helloworld', 'arg1', 'arg2'])
[    0.576048] Info: [appelfloader] <main.c @   82> Image at 0x403a00018, len 240936 bytes
[    0.596640] Info: [appelfloader] <main.c @  109> ELF program loaded to 0x400081000-0x4000bc2d8 (242392 B), entry at 0x4000a12b0
[    0.630812] CRIT: [appelfloader] <brk.c @   60> Cannot handle multiple user space heaps: Not implemented!
[0] /helloworld
[1] arg1
[2] arg2
```

### TODO:
- License stuff

### CODE REVIEW

**Comment by skuenzer** [comment]
HI @csvancea,

thanks a lot for this PR. In fact I am about to release also an implementation of launching application from VFS including support to automatically load the dynamic loader (`INTERP` field in ELF header of application). I can add you as reviewer for that PR, if okay?

Can you move the two commits
* [Simplify commandline argument passing](https://github.com/unikraft/app-elfloader/pull/10/commits/997497365f1e789d1a5f96b5c59b2bab3d2f6c0f)
* [Ignore build binaries and configuration file](https://github.com/unikraft/app-elfloader/pull/10/commits/e9f09a8151770ccddfccff1331aec9dffdfaf175)

to a separate PR? In fact there is this bug in the argument parsing code that drops `argv[0]`. This should not happen.

In case `CONFIG_APPELFLOADER_CUSTOMAPPNAME=y` is configured, the behavior with `argc=0` was intended. However, we could add a compatibility behavior within `elf_ctx_init()`, something that sets `""` as application name if `argc=0`. For the application `argc` would be set to one. Something along these lines:

```c
	/* ... */

	static const char null_progname[] = "";

	/* ... */

	/*
	 * argv + argc
	 */
	/* Same as envp, pushing NULL first */
	ukarch_rctx_stackpush(ctx, (long) NULL);
	if (argc) {
		for(i=argc-1; i>=0; --i)
			ukarch_rctx_stackpush(ctx, (uintptr_t) argv[i]);
		ukarch_rctx_stackpush(ctx, (long) argc);
	} else {
		ukarch_rctx_stackpush(ctx, (uintptr_t) null_progname);
		ukarch_rctx_stackpush(ctx, (long) 1);
	}

	/* ... */
```

**Comment by csvancea** [comment]
Sure, you can add me as a reviewer.

I have moved the command line bug fixes to #13. The suggested `argc=0` special case was not needed after all because the ELF loader simply requires that `argc >= 2` for when `CONFIG_APPELFLOADER_CUSTOMAPPNAME=y`, so it is impossible to have `argc=0` at that point in execution:

https://github.com/unikraft/app-elfloader/blob/a7556e5231535b6734f02fb15d7f5186fbcb9374/main.c#L69-L71

Now that you plan to release your own implementation for loading, I believe I no longer have to rebase this PR, right?

**Comment by razvand** [comment]
@csvancea, @skuenzer, is this PR still relevant?

**Comment by razvand** [comment]
Closing this as it was solved by #17

**Pull request closed without merging**
