### PR TITLE
Add KraftKit configuration files

### PR DESCRIPTION
**Pull request by razvand**
Add `kraft.yaml` - for general build, and `kraft.cloud.yaml` - for KraftCloud builds. `kraft.yaml` is currently mandatory for `kraft run`.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by mogasergiu** [comment]
Works for me.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Review by mogasergiu — APPROVED** [review]
Works for me.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
