### PR TITLE
scripts: Add support for running helloworld-cpp

### PR DESCRIPTION
**Pull request by willgao23**

### CODE REVIEW

**Review by StefanJum — CHANGES_REQUESTED** [review]
@willgao23 please remove the merge commit.

**Comment by willgao23** [comment]
@StefanJum removed merge commit and changed sign-off to have my email and not the github no-reply one.

**Comment by StefanJum** [comment]
@willgao23 there is conflict with the main branch since some other pr was merged, you will need to rebase this one.

**Review by razvand — CHANGES_REQUESTED** [review]
Add `run.yaml: ` as prefix to the commit message.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
