### PR TITLE
Binary compatiblity release

### PR DESCRIPTION
**Pull request by skuenzer**
This PR introduces the updated elfloader code that works with the latest changes of the uksched API (PR #564 of the Unikraft core). Instead of launching the ELF application on the same stack, the ELF application is executed in a new thread context.
The PR includes the following fixes:
 - Support of two TLS: Unikraft and userland (ELF application domain)
 - The application stack is properly setup (aux vector, arguments, ...)
 - Preparation for proper handling on application exit: ELF application gets launched in new process space

This PR depends on PR #5 .

### CODE REVIEW

**Review by razvand — APPROVED** [review]
@skuenzer, please solve the conflicts.

**Review by razvand — CHANGES_REQUESTED** [review]
@skuenzer, you need to rebase to solve the conflicts.

**Comment by skuenzer** [comment]
> @skuenzer, you need to rebase to solve the conflicts.

@razvand, here you go.

@razvand, yes, here you go. 😄

**Review by razvand — APPROVED** [review]
Thanks, @skuenzer.

This works. I also tested it with `posix-mmap`, i.e. replacing `LIBUKMMAP` with `LIBPOSIX_MMAP`. And it worked.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
